### ISSUE TITLE
async preloadEachDocument

### ISSUE THREAD

**Issue by davidsmejia** [autophytes/jotling#9]
Not really an issue just wanted the code formatting. Feel free to close this.

I had never run into this issue in the wild before so it made me curious... looks like if you want your async function to be non-blocking relative to the parent you need to have something block inside of it.

Maybe this is just an artifact of something else because I haven't found any documentation explaining this behavior.

here is a simple example:
```javascript
// some async function
const foo = async () => {
  console.log('- foo')
}

// an async function that should just return immediately  return but doesnt
// this is true for an arbitrary amount of `foo` calls
const nonAwait = async () => {
  foo()
  foo()
}

// an async function that executes the first `foo` then exits the function
// before the second `foo` is finished executing
const hasAwait = async () => {
  await foo()
  foo()
}

// same as hasAwait but shows it doesnt return until the first await
const hasLaterAwait = async () => {
  foo()
  foo()
  await foo()
  foo()
  foo()
}

console.log('nonAwait()')
nonAwait()
console.log('/nonAwait()')
console.log('\n')

console.log('hasAwait()')
hasAwait()
console.log('/hasAwait()')
console.log('\n')

console.log('hasLaterAwait()')
hasLaterAwait()
console.log('/hasLaterAwait()')
```

Output:
```console
nonAwait()
- foo
- foo
/nonAwait()


hasAwait()
- foo
/hasAwait()


hasLaterAwait()
- foo <== one of these is from hasAwait()
- foo
- foo
/hasLaterAwait()
- foo
- foo
- foo
```

Then in your project you could get around this issue lots of ways but here is one solution:
Code:
```javascript
	// Load an object with all raw document contents
	const loadAllDocuments = async () => {
		const newAllDocObj = await ipcRenderer.invoke(
			'read-all-documents',
			project.tempPath,
			'docs'
		);

		console.log('calling preload function');
		preloadEachDocument(newAllDocObj, setEditorArchives);
		console.log('ended preload function');
	};

	const preloadEachDocument = async (newAllDocObj, setEditorArchives) => {
		const archiveEntryPromises = Object
			.entries(newAllDocObj)
			.filter(([docName, docObj]) => docObj && Object.keys(docObj).length)
			.map(async ([docName, docObj]) => {
				// Convert to a valid docName editorState pairs
				const newContentState = convertFromRaw(docObj);
				const newEditorState = EditorState.createWithContent(newContentState);
				return [
					docName,
					{
						editorState: newEditorState,
						scrollY: 0,
					}
				]
			})
		const archiveEntries = await Promise.all(archiveEntryPromises)
		setEditorArchives(Object.fromEntries(archiveEntries))
		console.log('ended preload promise')
	}
```
Output:
```console
...
appMgmt.jsx:178 function after loadAllDocuments
...
appMgmt.jsx:94 calling preload function
appMgmt.jsx:96 ended preload function
...
appMgmt.jsx:111 ended preload promise
...
```

However if you map synchronously and remove the await Promise.all you get the initial problem again
(loadAllDocuments is the same as above here and ommited)
Code:
```javascript
	const preloadEachDocument = async (newAllDocObj, setEditorArchives) => {
		const archiveEntry = Object
			.entries(newAllDocObj)
			.filter(([docName, docObj]) => docObj && Object.keys(docObj).length)
			.map(([docName, docObj], i) => {
				// Convert to a valid docName editorState pairs
				const newContentState = convertFromRaw(docObj);
				const newEditorState = EditorState.createWithContent(newContentState);
				return [
					docName,
					{
						editorState: newEditorState,
						scrollY: 0,
					}
				]
			})
		setEditorArchives(Object.fromEntries(archiveEntry))
		console.log('end preload not promise all')
	}

```
Output:
``` console
...
appMgmt.jsx:177 function after loadAllDocuments
...
appMgmt.jsx:94 calling preload function
...
appMgmt.jsx:110 end preload not promise all
appMgmt.jsx:96 ended preload function
...
```

Good luck with your app!

**Comment by autophytes** [comment]
David thank you so much for the work you put into this example! I saw this very late - I haven't been monitoring Github's Issues yet since the app is definitely full of them right now, and I just realized my mistake. I'll need to set up some sort of alerts for the future. 

I'll be honest, that the " - foo" from the hasAwait() shows up _after_ its own closing console log ends but _before_ the closing console log of the hasLaterAwait() is kind of baffling to me. Apparently there are facets that I still don't quite understand.

Ultimately the behavior I was looking for was, whenever there are free resources because the user isn't doing anything, preload the next document. Once that is finished, if there are free resources, do the next one. I'm not 100% sure how async / await affects the call stack, but what a 0-delay setTimeout does is basically wait until the stack is completely clear, then pops on the task. The solution I ultimately went with used this and once one document was preloaded, it queued up the next one. This way, any typing the user did could slip in between preloading with minimal lag instead of being totally blocked. You can see my solution at https://github.com/autophytes/jotling/blob/724933ab4b61e1704dfb4f4e8ed864cbfefa0a4e/src/components/appMgmt.jsx#L473.

Thanks again for looking into this!
